// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipCreator.Data;

#nullable disable

namespace ShipCreator.Migrations
{
    [DbContext(typeof(ShipCreatorContext))]
    [Migration("20250304215431_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("ShipCreator.Models.Ship", b =>
                {
                    b.Property<Guid>("ShipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int>("NauticalMilage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PledgedFaction")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ShipID");

                    b.ToTable("Ship");
                });
#pragma warning restore 612, 618
        }
    }
}
